# Generated by Django 4.1.1 on 2022-10-14 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_alter_album_isapproved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='AlbumArtist',
            new_name='album_artist',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='AlbumCreationDate',
            new_name='album_creation_date',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='AlbumName',
            new_name='album_name',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='AlbumReleaseTime',
            new_name='album_release_time',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='isApproved',
            new_name='is_approved',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='Price',
            new_name='price',
        ),
    ]
