# Generated by Django 4.1.1 on 2022-10-13 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stagename', models.CharField(max_length=100, unique=True)),
                ('sociallink', models.URLField(blank=True)),
            ],
        ),
    ]
