# Generated by Django 4.1.1 on 2022-10-14 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='sociallink',
            new_name='social_link',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='stagename',
            new_name='stage_name',
        ),
    ]
